name: AlexSpringer99 DevOps
run-name: ${{ github.actor }} is creating a runner
on:
  push:
  workflow_dispatch:
   
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: git pull https://github.com/alexspringer99/KatalonTestRepo.git
