name: AlexSpringer99 DevOps
run-name: ${{ github.actor }} is creating a runner
on:
  push:
  workflow_dispatch:
   
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/Hagenberg-DevOps-And-Secure-Coding/devops-workshop-alexspringer99.git
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
