name: AlexSpringer99 DevOps
run-name: ${{ github.actor }} is creating a runner
on:
  push:
  workflow_dispatch:
   
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
